kind: Service
apiVersion: v1
metadata:
  name: notes-app-fe-service
  namespace: notes-app
spec:
  selector:
    app: notes-app-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  