kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-backend-dep
  namespace: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      name: python-backend-pod
      labels:
        app: python-backend
    spec:
      containers:
        - name: python-backend
          image: kunwaranas/fullstack-python:20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080