kind: Service
apiVersion: v1
metadata:
  name: python-backend-svc
  namespace: notes-app
spec:
  selector:
    app: python-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP